import { FormEvent, useEffect, useState } from 'react';
import { LogOut, Plus, Save } from 'lucide-react';
import { createPhoneUnit, createTeamUser, getCustomers, getPhoneUnits, getTeamUsers, saveCustomer, saveProduct, setTeamUserStatus, type Customer, type PhoneUnit, type Product, type Role, type TeamUser } from './api';

const emptyProduct={sku:'',name:'',category:'Chargers',price:'',stock:'',barcode:'',imei:''};
const emptyCustomer={name:'',contact_name:'',phone:'',email:''};
const emptyTeamUser={name:'',email:'',password:'',role:'staff' as Role};
const emptyPhoneUnit={product_id:'',imei:'',colour:'',storage:'',supplier_name:'',purchase_cost:'',warranty_status:'12-month warranty'};

export function AdminPage({products,onChanged,onLogout}:{products:Product[];onChanged:()=>void;onLogout:()=>void}) {
 const [customers,setCustomers]=useState<Customer[]>([]); const [teamUsers,setTeamUsers]=useState<TeamUser[]>([]);
 const [productForm,setProductForm]=useState(emptyProduct); const [productId,setProductId]=useState<number>();
 const [customerForm,setCustomerForm]=useState(emptyCustomer); const [customerId,setCustomerId]=useState<number>();
 const [teamForm,setTeamForm]=useState(emptyTeamUser);
 const [phoneUnits,setPhoneUnits]=useState<PhoneUnit[]>([]); const [phoneUnitForm,setPhoneUnitForm]=useState(emptyPhoneUnit);
 const [error,setError]=useState(''); const [notice,setNotice]=useState('');
 const loadCustomers=()=>getCustomers(new AbortController().signal).then(setCustomers).catch((reason:Error)=>setError(reason.message));
 const loadTeam=()=>getTeamUsers(new AbortController().signal).then(setTeamUsers).catch((reason:Error)=>setError(reason.message));
 const loadPhoneUnits=()=>getPhoneUnits(new AbortController().signal).then(setPhoneUnits).catch((reason:Error)=>setError(reason.message));
 useEffect(()=>{void loadCustomers();void loadTeam();void loadPhoneUnits();},[]);
 const submitProduct=async(e:FormEvent)=>{e.preventDefault();setError('');setNotice('');try{await saveProduct({...productForm,price:Number(productForm.price).toFixed(2),stock:Number(productForm.stock),barcode:productForm.barcode||null,imei:productForm.imei||null},productId);setNotice(productId?'Product updated.':'Product added.');setProductForm(emptyProduct);setProductId(undefined);onChanged();}catch(reason){setError(reason instanceof Error?reason.message:'Product could not be saved.');}};
 const submitCustomer=async(e:FormEvent)=>{e.preventDefault();setError('');setNotice('');try{await saveCustomer(customerForm,customerId);setNotice(customerId?'Customer updated.':'Customer added.');setCustomerForm(emptyCustomer);setCustomerId(undefined);await loadCustomers();}catch(reason){setError(reason instanceof Error?reason.message:'Customer could not be saved.');}};
 const submitTeamUser=async(e:FormEvent)=>{e.preventDefault();setError('');setNotice('');try{await createTeamUser(teamForm);setNotice('Staff account created. They can now sign in.');setTeamForm(emptyTeamUser);await loadTeam();}catch(reason){setError(reason instanceof Error?reason.message:'Staff account could not be created.');}};
 const submitPhoneUnit=async(e:FormEvent)=>{e.preventDefault();setError('');setNotice('');try{await createPhoneUnit({...phoneUnitForm,product_id:Number(phoneUnitForm.product_id),supplier_name:phoneUnitForm.supplier_name||null,purchase_cost:Number(phoneUnitForm.purchase_cost).toFixed(2)});setNotice('Phone unit added and available for sale.');setPhoneUnitForm(emptyPhoneUnit);await loadPhoneUnits();onChanged();}catch(reason){setError(reason instanceof Error?reason.message:'Phone unit could not be saved.');}};
 const toggleTeamUser=async(user:TeamUser)=>{setError('');setNotice('');try{await setTeamUserStatus(user.id,!user.is_active);setNotice(user.is_active?'Account deactivated.':'Account activated.');await loadTeam();}catch(reason){setError(reason instanceof Error?reason.message:'Account status could not be updated.');}};
 const generateBarcode=()=>{let barcode='';do{barcode=`OD-${Date.now().toString().slice(-8)}-${Math.floor(1000+Math.random()*9000)}`;}while(products.some(product=>product.barcode===barcode));setProductForm({...productForm,barcode});setNotice('Unique barcode generated.');};
 const selectProduct=(product:Product)=>{setProductId(product.id);setProductForm({sku:product.sku,name:product.name,category:product.category,price:product.price,stock:String(product.stock),barcode:product.barcode||'',imei:product.imei||''});setNotice(`Editing ${product.name}.`);};
 const selectCustomer=(customer:Customer)=>{setCustomerId(customer.id);setCustomerForm({name:customer.name,contact_name:customer.contact_name,phone:customer.phone,email:customer.email});setNotice(`Editing ${customer.name}.`);};
 return <section className="admin-grid">
  <section className="panel admin-card"><div className="section-heading"><div><div className="eyebrow">ADMIN ACCESS</div><h2>{productId?'Edit product':'Add a product'}</h2><p>Product and stock changes are restricted to admins.</p></div><button className="admin-signout" onClick={onLogout}><LogOut size={15}/>Sign out</button></div>
   <form onSubmit={submitProduct} className="admin-form"><label>SKU<input required value={productForm.sku} onChange={e=>setProductForm({...productForm,sku:e.target.value})}/></label><label>Product name<input required value={productForm.name} onChange={e=>setProductForm({...productForm,name:e.target.value})}/></label><label>Category<select value={productForm.category} onChange={e=>setProductForm({...productForm,category:e.target.value})}>{['Phones','Chargers','Cables','Cases','Headphones'].map(category=><option key={category}>{category}</option>)}</select></label><div className="admin-pair"><label>Barcode<div className="identifier-field"><input value={productForm.barcode} onChange={e=>setProductForm({...productForm,barcode:e.target.value})} placeholder="Scan or type barcode"/><button type="button" className="button secondary" onClick={generateBarcode}>Generate</button></div></label><label>IMEI (single phone)<input value={productForm.imei} onChange={e=>setProductForm({...productForm,imei:e.target.value})} placeholder="15-digit IMEI"/></label></div><div className="admin-pair"><label>Price (USD)<input required value={productForm.price} type="number" min="0" step="0.01" onChange={e=>setProductForm({...productForm,price:e.target.value})}/></label><label>Stock on hand<input required value={productForm.stock} type="number" min="0" step="1" onChange={e=>setProductForm({...productForm,stock:e.target.value})}/></label></div><div className="admin-form-actions"><button className="button primary"><Save size={16}/>{productId?'Save product':'Add product'}</button>{productId&&<button type="button" className="button secondary" onClick={()=>{setProductForm(emptyProduct);setProductId(undefined);}}>Cancel</button>}</div></form>
   <div className="admin-products">{products.map(product=><button key={product.id} onClick={()=>selectProduct(product)}><span><strong>{product.name}</strong><small>{product.sku} · {product.stock} in stock</small></span><span>Edit</span></button>)}</div>
  </section>
  <section className="panel admin-card"><div className="section-heading"><div><div className="eyebrow">INDIVIDUAL PHONE INVENTORY</div><h2>Add a phone unit</h2><p>Each device has its own IMEI and availability status.</p></div><Plus/></div>
   <form onSubmit={submitPhoneUnit} className="admin-form"><label>Phone model<select required value={phoneUnitForm.product_id} onChange={e=>setPhoneUnitForm({...phoneUnitForm,product_id:e.target.value})}><option value="">Choose a phone product</option>{products.filter(product=>product.category==='Phones').map(product=><option key={product.id} value={product.id}>{product.name} · {product.sku}</option>)}</select></label><div className="admin-pair"><label>IMEI<input required minLength={14} value={phoneUnitForm.imei} onChange={e=>setPhoneUnitForm({...phoneUnitForm,imei:e.target.value})}/></label><label>Colour<input required value={phoneUnitForm.colour} onChange={e=>setPhoneUnitForm({...phoneUnitForm,colour:e.target.value})}/></label></div><div className="admin-pair"><label>Storage<input required value={phoneUnitForm.storage} onChange={e=>setPhoneUnitForm({...phoneUnitForm,storage:e.target.value})} placeholder="128GB"/></label><label>Purchase cost (USD)<input required type="number" min="0" step="0.01" value={phoneUnitForm.purchase_cost} onChange={e=>setPhoneUnitForm({...phoneUnitForm,purchase_cost:e.target.value})}/></label></div><div className="admin-pair"><label>Supplier<input value={phoneUnitForm.supplier_name} onChange={e=>setPhoneUnitForm({...phoneUnitForm,supplier_name:e.target.value})}/></label><label>Warranty<input required value={phoneUnitForm.warranty_status} onChange={e=>setPhoneUnitForm({...phoneUnitForm,warranty_status:e.target.value})}/></label></div><button className="button primary"><Save size={16}/>Add phone unit</button></form>
   <div className="admin-products">{phoneUnits.map(unit=><div className="team-user" key={unit.id}><span><strong>{unit.imei}</strong><small>{unit.colour} · {unit.storage} · {unit.status}</small></span><span>{unit.purchase_cost} USD</span></div>)}{!phoneUnits.length&&<p className="empty-inline">Add a phone product, then register each physical phone here.</p>}</div>
  </section>
  <section className="panel admin-card"><div className="section-heading"><div><div className="eyebrow">CUSTOMER RECORDS</div><h2>{customerId?'Edit customer':'Add a customer'}</h2><p>Manage the customer list used for orders.</p></div><Plus/></div>
   <form onSubmit={submitCustomer} className="admin-form"><label>Business name<input required value={customerForm.name} onChange={e=>setCustomerForm({...customerForm,name:e.target.value})}/></label><label>Contact name<input required value={customerForm.contact_name} onChange={e=>setCustomerForm({...customerForm,contact_name:e.target.value})}/></label><div className="admin-pair"><label>Phone<input required value={customerForm.phone} onChange={e=>setCustomerForm({...customerForm,phone:e.target.value})}/></label><label>Email<input required type="email" value={customerForm.email} onChange={e=>setCustomerForm({...customerForm,email:e.target.value})}/></label></div><div className="admin-form-actions"><button className="button primary"><Save size={16}/>{customerId?'Save customer':'Add customer'}</button>{customerId&&<button type="button" className="button secondary" onClick={()=>{setCustomerForm(emptyCustomer);setCustomerId(undefined);}}>Cancel</button>}</div></form>
   <div className="admin-products">{customers.map(customer=><button key={customer.id} onClick={()=>selectCustomer(customer)}><span><strong>{customer.name}</strong><small>{customer.contact_name} · {customer.email}</small></span><span>Edit</span></button>)}</div>
  </section>
  <section className="panel admin-card team-card"><div className="section-heading"><div><div className="eyebrow">TEAM ACCOUNTS</div><h2>Add a staff login</h2><p>Staff can create and process orders. They cannot change the catalog or settings.</p></div><Plus/></div>
   <form onSubmit={submitTeamUser} className="admin-form"><label>Staff member name<input required value={teamForm.name} onChange={e=>setTeamForm({...teamForm,name:e.target.value})}/></label><label>Work email<input required type="email" value={teamForm.email} onChange={e=>setTeamForm({...teamForm,email:e.target.value})}/></label><label>Temporary password<input required type="password" minLength={12} value={teamForm.password} onChange={e=>setTeamForm({...teamForm,password:e.target.value})}/><small>Use at least 12 characters. Share it privately with the staff member.</small></label><label>Access level<select value={teamForm.role} onChange={e=>setTeamForm({...teamForm,role:e.target.value as Role})}><option value="staff">Staff - orders only</option><option value="admin">Admin - full access</option></select></label><div className="admin-form-actions"><button className="button primary"><Save size={16}/>Create account</button></div></form>
   <div className="admin-products">{teamUsers.map(user=><div className="team-user" key={user.id}><span><strong>{user.name}</strong><small>{user.email} - {user.role} - {user.is_active?'Active':'Inactive'}</small></span><button className="button secondary" type="button" onClick={()=>toggleTeamUser(user)}>{user.is_active?'Deactivate':'Activate'}</button></div>)}{!teamUsers.length&&<p className="empty-inline">No database team accounts yet. Create your first staff login above.</p>}</div>
  </section>
  {(error||notice)&&<div className={error?'admin-error':'admin-notice'} role={error?'alert':'status'}>{error||notice}</div>}
 </section>;
}

