import { useEffect, useState } from 'react';
import { FileUp, Upload } from 'lucide-react';
import { applyProductImport, getImportHistory, previewProductImport, type ImportRecord, type ProductImportPreview } from './api';
export function ImportPage({onImported}:{onImported:()=>void}) {
 const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<ProductImportPreview|null>(null),[history,setHistory]=useState<ImportRecord[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=()=>getImportHistory(new AbortController().signal).then(setHistory).catch(()=>{}); useEffect(()=>{void load();},[]);
 const review=async()=>{if(!file)return;setBusy(true);try{setPreview(await previewProductImport(file));}catch(e){setMessage(e instanceof Error?e.message:'Could not read CSV.');}finally{setBusy(false);}};
 const apply=async()=>{if(!file||!preview||preview.errors.length)return;setBusy(true);try{const r=await applyProductImport(file);setPreview(r);setMessage(`${r.valid_rows} rows imported.`);onImported();void load();}catch(e){setMessage(e instanceof Error?e.message:'Import failed.');}finally{setBusy(false);}};
 return <section className="import-page"><section className="panel import-card"><div className="section-heading"><div><h2>Upload product CSV</h2><p>Preview every row before updating the catalog.</p></div><FileUp size={22}/></div><div className="import-content"><label className="file-drop"><Upload size={25}/><strong>{file?file.name:'Choose a CSV file'}</strong><small>sku, name, category, price, stock</small><input type="file" accept=".csv,text/csv" onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null);setMessage('');}}/></label><button className="button primary" disabled={!file||busy} onClick={review}>{busy?'Reading…':'Preview CSV'}</button>{message&&<p className="import-message">{message}</p>}</div></section>{preview&&<section className="panel import-card"><div className="section-heading"><div><h2>Review import</h2><p>{preview.valid_rows} valid rows. Nothing changes until confirmation.</p></div>{!preview.errors.length&&<button className="button primary" disabled={busy} onClick={apply}>Confirm import</button>}</div>{preview.errors.length?<ul className="import-errors">{preview.errors.map(e=><li key={e}>{e}</li>)}</ul>:<div className="table-scroll"><table><tbody>{preview.rows.map(r=><tr key={r.row}><td>{r.sku}</td><td>{r.name}</td><td>{r.stock}</td><td>{r.action}</td></tr>)}</tbody></table></div>}</section>}<section className="panel import-card"><div className="section-heading"><div><h2>Import history</h2><p>Confirmed catalog updates only.</p></div></div>{history.length?<div className="table-scroll"><table><tbody>{history.map(r=><tr key={r.id}><td>{r.filename}</td><td>{r.imported_by}</td><td>+{r.created_rows} / updated {r.updated_rows}</td><td>{new Date(r.imported_at).toLocaleString()}</td></tr>)}</tbody></table></div>:<div className="operations-empty"><p>No confirmed imports yet.</p></div>}</section></section>;
}
