import { useEffect, useState } from 'react';
import { ChevronDown, MessageCircle, Pencil, RefreshCw, Send, Sparkles } from 'lucide-react';
import { getInboxMessages, type InboxMessage, type Product } from './api';
type DraftLine={product_id:number;quantity:number};
export function MessageInboxPage({products,onCreateDraft}:{products:Product[];onCreateDraft:(lines:DraftLine[])=>void}) {
 const [messages,setMessages]=useState<InboxMessage[]>([]),[open,setOpen]=useState<number|null>(null),[editing,setEditing]=useState<number|null>(null),[draft,setDraft]=useState<DraftLine[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const load=()=>{const controller=new AbortController();setLoading(true);setError('');getInboxMessages(controller.signal).then(setMessages).catch((reason:Error)=>{if(reason.name!=='AbortError'&&!controller.signal.aborted)setError(reason.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return controller;};
 useEffect(()=>{const controller=load();return()=>controller.abort();},[]);
 const start=(message:InboxMessage)=>{setOpen(message.id);setEditing(message.id);setDraft(message.analysis.items.filter(item=>item.suggested_product&&item.quantity).map(item=>({product_id:products.find(product=>product.name===item.suggested_product?.name)?.id||0,quantity:item.quantity||1})).filter(item=>item.product_id));};
 return <section className="message-inbox"><section className="panel"><div className="section-heading"><div><div className="eyebrow">MESSAGE CHANNEL</div><h2>Incoming customer messages</h2><p>Messages are analyzed automatically. Review or edit the suggestion before creating a draft.</p></div><button className="button secondary" onClick={()=>load()} disabled={loading}><RefreshCw size={15}/>Refresh</button></div>{error?<div className="order-banner error">{error}</div>:<div className="message-list">{messages.map(message=>{const expanded=open===message.id,edit=editing===message.id;return <article className="message-row" key={message.id}><span className="message-icon"><MessageCircle size={18}/></span><div><strong>{message.sender_phone}</strong><p>{message.message_text}</p>{expanded&&<div className="message-analysis"><strong><Sparkles size={14}/>AI suggestion</strong>{edit?draft.map((line,index)=><p key={index}><select value={line.product_id} onChange={event=>setDraft(draft.map((item,itemIndex)=>itemIndex===index?{...item,product_id:Number(event.target.value)}:item))}>{products.map(product=><option value={product.id} key={product.id}>{product.name}</option>)}</select><input type="number" min="1" value={line.quantity} onChange={event=>setDraft(draft.map((item,itemIndex)=>itemIndex===index?{...item,quantity:Number(event.target.value)}:item))}/></p>):message.analysis.items.map((item,index)=><p key={index}>{item.quantity??'?'} × {item.suggested_product?.name||item.requested_description}<small>{item.match_status==='matched'?'Catalog match found':'Needs staff confirmation'}</small></p>)}{edit&&<button className="button primary" disabled={!draft.length} onClick={()=>onCreateDraft(draft)}><Send size={14}/>Send as order draft</button>}</div>}</div><div className="message-actions"><button className="button secondary" onClick={()=>setOpen(expanded?null:message.id)}>{expanded?'Hide':'View AI analysis'}<ChevronDown size={15}/></button><button className="button primary" onClick={()=>start(message)}><Pencil size={14}/>Edit analysis</button></div></article>})}</div>}</section></section>;
}
